## Nome: Mayara Cristina
## Matrícula: 574

---

# Atividade 2 - Algoritmos e Métodos Numéricos, Erros, Medidas e Fontes

Uma equipe de desenvolvedores e engenheiros está projetando um sistema de monitoramento térmico em tempo real para as CPUs de um Data Center. O objetivo do sistema é acionar o resfriamento de emergência sempre que a temperatura da CPU atingir o limite crítico de segurança, definido como $85\text{ }^\circ\text{C}$ por um sensor óptico padrão de calibração de altíssima precisão.
Para baratear o custo, a equipe testou 6 módulos de sensores de temperatura IoT diferentes (série de nós de sensores $S_1$ a $S_6$). Devido a limitações de hardware — como a resolução do Conversor Analógico-Digital (ADC) do microcontrolador (erro de quantização e truncamento), ruído eletromagnético e tolerância dos componentes —, os valores digitais lidos por cada sensor apresentaram pequenas divergências em relação ao valor real de referência.



Os resultados dos sensores estão na tabela abaixo:

| Módulo de Sensor | Temperatura Lida (°C) |
| --- | --- |
| Sensor S1 | 84,820 |
| Sensor S2 | 85,150 |
| Sensor S3 | 84,985 |
| Sensor S4 | 85,040 |
| Sensor S5 | 85,310 |
| Sensor S6 | 84,910 |


Seu objetivo é analisar esses dados e calcular diferentes métricas de erro, usando as bibliotecas pandas e numpy.

---

In [ ]:
from IPython.display import display
# Importando bibliotecas

#Analise de dados
import pandas as pd
import numpy as np

In [ ]:
Valor_referencia = 85
#Tabela de dados
tabela = {
    "Sensor": [
        "Sensor S1",
        "Sensor S2",
        "Sensor S3",
        "Sensor S4",
        "Sensor S5",
        "Sensor S6",
    ],
    "Temp_Lida (°C)": [84.820, 85.150, 84.985, 85.040, 85.310, 84.910],
}

dados = pd.DataFrame(tabela)
display(dados)

      Sensor  Temp_Lida (°C)
0  Sensor S1          84.820
1  Sensor S2          85.150
2  Sensor S3          84.985
3  Sensor S4          85.040
4  Sensor S5          85.310
5  Sensor S6          84.910

### Parte 1 - Erro Absoluto, Erro Relativo e Erro Percentual

Calcule o Erro Absoluto, o Erro Relativo e o Erro Percentual dos valores medidos.

In [ ]:
dados['Erro_Absoluto'] = abs(Valor_referencia - dados['Temp_Lida (°C)'])
display(dados)

      Sensor  Temp_Lida (°C)  Erro_Absoluto
0  Sensor S1          84.820          0.180
1  Sensor S2          85.150          0.150
2  Sensor S3          84.985          0.015
3  Sensor S4          85.040          0.040
4  Sensor S5          85.310          0.310
5  Sensor S6          84.910          0.090

In [ ]:
dados['Erro_Relativo'] = dados['Erro_Absoluto'] / abs(dados['Temp_Lida (°C)'])
display(dados)

      Sensor  Temp_Lida (°C)  Erro_Absoluto  Erro_Relativo
0  Sensor S1          84.820          0.180       0.002122
1  Sensor S2          85.150          0.150       0.001762
2  Sensor S3          84.985          0.015       0.000177
3  Sensor S4          85.040          0.040       0.000470
4  Sensor S5          85.310          0.310       0.003634
5  Sensor S6          84.910          0.090       0.001060

In [ ]:
dados['Erro_Percentual'] = dados['Erro_Relativo'] * 100
display(dados)

      Sensor  Temp_Lida (°C)  Erro_Absoluto  Erro_Relativo  Erro_Percentual
0  Sensor S1          84.820          0.180       0.002122         0.212214
1  Sensor S2          85.150          0.150       0.001762         0.176160
2  Sensor S3          84.985          0.015       0.000177         0.017650
3  Sensor S4          85.040          0.040       0.000470         0.047037
4  Sensor S5          85.310          0.310       0.003634         0.363381
5  Sensor S6          84.910          0.090       0.001060         0.105995

**Formulário para cálculo de erros**

- Erro Absoluto:  
$$E_a = |V_t - V_m|$$

- Erro Relativo:  
$$E_r = \frac{E_a}{|V_m|}$$

- Erro Percentual:  
$$E_p = E_r \times 100\%$$

Onde:  
- $V_t$ = valor teórico de referência  
- $V_m$ = valor medido pelo sensor

### Parte 2 - Arredondamento e Truncamento

Um engenheiro biomédico está testando um novo sensor para um oxímetro de pulso hospitalar (aparelho que mede a saturação de oxigênio no sangue, $SpO_2$).

O sensor faz a medição com alta precisão (quatro casas decimais), mas o visor do aparelho só tem espaço para mostrar o número arredondado com duas casas decimais.

As medições feitas pelo sensor em cinco pacientes foram:

| Paciente | Oxigênio Medido (%) |
| --- | --- |
| P1 | 92.3456 |
| P2 | 98.8765 |
| P3 | 95.5555 |
| P4 | 97.4999 |
| P5 | 90.0501 |

### 1 - Fazer um DataFrame para organização visual dos dados

In [ ]:
import pandas as pd

# Dados dos pacientes
dados = {
    "Paciente": ["P1", "P2", "P3", "P4", "P5"],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 97.4999, 90.0501]
}

# Criando o DataFrame
df = pd.DataFrame(dados)

# Exibindo o DataFrame
display(df)

  Paciente  Oxigênio Medido (%)
0       P1              92.3456
1       P2              98.8765
2       P3              95.5555
3       P4              97.4999
4       P5              90.0501

### 2 - Arredonde todos os valores para 2 casas decimais

In [ ]:
import pandas as pd

# Criando o DataFrame
dados = {
    "Paciente": ["P1", "P2", "P3", "P4", "P5"],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 97.4999, 90.0501]
}

df = pd.DataFrame(dados)

# Arredondando os valores numéricos para 2 casas decimais
df["Oxigênio Medido (%)"] = df["Oxigênio Medido (%)"].round(2)

# Exibindo o DataFrame
display(df)

  Paciente  Oxigênio Medido (%)
0       P1                92.35
1       P2                98.88
2       P3                95.56
3       P4                97.50
4       P5                90.05

### 3 - Trunque os valores para 1 casa decimal

In [ ]:
import pandas as pd
import numpy as np

# Criando o DataFrame
dados = {
    "Paciente": ["P1", "P2", "P3", "P4", "P5"],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 97.4999, 90.0501]
}

df = pd.DataFrame(dados)

# Truncando para 1 casa decimal
df["Oxigênio Medido (%)"] = np.trunc(df["Oxigênio Medido (%)"] * 10) / 10

# Exibindo o DataFrame
display(df)

  Paciente  Oxigênio Medido (%)
0       P1                 92.3
1       P2                 98.8
2       P3                 95.5
3       P4                 97.4
4       P5                 90.0

### 4 - Qual é o valor inteiro mais próximo para cada?

In [ ]:
import pandas as pd
import numpy as np

# Criando o DataFrame
dados = {
    "Paciente": ["P1", "P2", "P3", "P4", "P5"],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 97.4999, 90.0501]
}

df = pd.DataFrame(dados)

# Arredondando para o inteiro mais próximo
df["Inteiro Mais Próximo"] = np.round(df["Oxigênio Medido (%)"]).astype(int)

display(df)

  Paciente  Oxigênio Medido (%)  Inteiro Mais Próximo
0       P1              92.3456                    92
1       P2              98.8765                    99
2       P3              95.5555                    96
3       P4              97.4999                    97
4       P5              90.0501                    90

### 5 - Mostre os resultados dentro de uma tabela

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

# Criando o DataFrame
dados = {
    "Paciente": ["P1", "P2", "P3", "P4", "P5"],
    "Oxigênio Medido (%)": [92.3456, 98.8765, 95.5555, 97.4999, 90.0501]
}

df = pd.DataFrame(dados)

# Arredondar para 2 casas
df["Arredondado (2 casas)"] = np.round(df["Oxigênio Medido (%)"], 2)

# Truncar para 1 casa
df["Truncado (1 casa)"] = np.trunc(df["Oxigênio Medido (%)"] * 10) / 10

# Inteiro mais próximo
df["Inteiro mais próximo"] = np.round(df["Oxigênio Medido (%)"]).astype(int)

# Exibir tabela
display(df)

,Paciente,Oxigênio Medido (%),Arredondado (2 casas),Truncado (1 casa),Inteiro mais próximo
0,P1,92.3456,92.35,92.3,92
1,P2,98.8765,98.88,98.8,99
2,P3,95.5555,95.56,95.5,96
3,P4,97.4999,97.50,97.4,97
4,P5,90.0501,90.05,90.0,90




<span style="font-size:90%">

**Guia Rápido: Arredondamento e Truncamento**

- Arredondar para n casas decimais: `dados["Comprimento Medido (cm)"].round(0)`  
- Truncar para n casas decimais: `np.trunc(dados["Comprimento Medido (cm)"] * 10) / 10`  
- Arredondar para inteiro mais próximo: `dados["Comprimento Medido (cm)"].round(0).astype(int)`

</span>

## Parte Teórica

**Questão 1.**

Julgue as afirmativas abaixo como V (Verdadeiro) ou F (Falso) e justifique as que forem Falsas.

1. O erro absoluto nos dá a exata noção do impacto da falha, independentemente da ordem de grandeza do valor medido.

2. O instrumento de medida escolhido para medir uma grandeza deve ser coerente com aquilo que se deseja medir.

3. O erro percentual é calculated multiplicando o erro absoluto por 100%.

4. Erros aleatórios não podem ser eliminados por calibração de instrumentos, mas podem ser minimizados através de repetições e métodos estatísticos (como a média).

5. O número de algoritmos significativos de uma grandeza é determinado pela sua incerteza.

**Resposta:**
1. F = O erro absoluto não indica o impacto da falha independentemente da ordem de grandeza. Um erro absoluto de 1 unidade pode ser muito pequeno para uma medida de 1000, mas muito grande para uma medida de 2. Para avaliar o impacto, utiliza-se o erro relativo ou o erro percentual.
2. V
3. F = O erro percentual não é obtido multiplicando o erro absoluto por 100. A fórmula correta é: Ep=Er×100%
4. V
5. V

**Questão 2.**

Quando você faz a medição de alguma grandeza, com um instrumento de medição qualquer, em qual conjunto cai a medida que você
obteve?

Conjunto dos números Naturais, Inteiros, Racionais, Irracionais, Reais ou Complexos? Justifique sua resposta

**Resposta:**
Conjunto dos números racionais (ℚ).
Ao realizar uma medição com um instrumento, o valor obtido é expresso por um número decimal finito (ou com uma quantidade limitada de casas decimais), como por exemplo 25,4 cm, 3,14 V ou 98,7%. Esses valores podem ser escritos na forma de fração, portanto pertencem ao conjunto dos números racionais.